// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xowphjybrohcvcnbhueo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvd3Boanlicm9oY3ZjbmJodWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzA2MDIsImV4cCI6MjA2NjQ0NjYwMn0.R6vzHEeoXVfBNq85C7oOQf4s-Hja-_H74TngXVvP7CU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});